services:
  server:
    restart: always
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    restart: always
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_PORT=${API_PORT}
